image: ubuntu:14.04

before_script:
    - apt-get update -qy
    - apt-get install -qy python-dev python-pip
    - pip install -r requirements.txt

stages:
    - build
    - test
    - deploy

cache:
    pip: true
    apt: true

build:c:
    stage: build
    script:
        - python setup.py build_ext develop

build:cython:
    stage: build
    script:
        - pip install cython --install-option=--no-cython-compile
        - python setup.py build_ext develop --use-cython

test:tox:
    stage: test
    script:
        - pip install tox
        - pip install pytest
        - tox

pages:
    stage: deploy
    script:
        - pip install sphinx
        - python setup.py build_ext develop --use-cython
        - cd docs
        - make html
        - cd ../
        - mkdir public
        - mv -r docs/build/html/* public/
    artifacts:
        paths:
            - public
    only:
        - master
