before_script:
    - pip install -r requirements.txt

nocython:
    script:
        - python setup.py develop

withcython:
    script:
        - pip install cython
        - python setup.py develop --use-cython
