image: ubuntu:14.04

before_script:
    - apt-get update -qy
    - apt-get install -qy python-dev python-pip
    - pip install -r requirements.txt

stages:
    - build
    - test
    - deploy

cache:
    pip: true
    apt: true
    untracked: true

build:c:
    stage: build
    script:
        - python setup.py build_ext --inplace
    artifacts:
        paths:
            - proj/**/*.so

build:cython:
    stage: build
    script:
        - pip install cython --install-option=--no-cython-compile
        - python setup.py build_ext --inplace --use-cython

test:tox:
    stage: test
    dependencies:
        - build:c
    script:
        - pip install tox
        - pip install pytest
        - python setup.py build_ext --inplace
        - tox

pages:
    stage: deploy
    dependencies:
        - build:c
    script:
        - pip install sphinx
        - cd docs
        - make html
        - cd ../
        - mkdir public
        - mv -r docs/build/html/* public/
    artifacts:
        paths:
            - public
    only:
        - master
