before_script:
    - apt-get update -qy
    - apt-get install -qy python-dev python-pip
    - pip install -r requirements.txt

nocython:
    script:
        - python setup.py develop

withcython:
    script:
        - pip install cython
        - python setup.py develop --use-cython
