language: python

cache:
    apt: true
    pip: true

before_install:
    - sudo apt-get update -qy
    - sudo apt-get install -qy python-dev python-pip

install:
    - pip install -r requirements.txt
    - pip install tox
    - pip install sphinx

script:
    - pip install cython --install-option=--no-cython-compile
    - python setup.py build_ext --inplace
    - python setup.py build_ext --inplace --use-cython
    - tox
